version: '2'
services:
  visionmongoelastickafka-mongodb:
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/visionmongoelastickafka/mongodb/:/data/db/
